services:
  - type: web
    name: dropstream
    runtime: docker
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD
        value: "1"
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /ms-playwright
      - key: REMOTE_BROWSER_ENABLED
        value: "true"
      - key: REMOTE_BROWSER_FPS
        value: "1"
      - key: REMOTE_BROWSER_JPEG_QUALITY
        value: "58"
