require('dotenv').config();
const express=require('express'),compression=require('compression'),path=require('path');
const app=express(),PORT=process.env.PORT||3000;
const API_BASE_URL=(process.env.API_BASE_URL||'').replace(/\/$/,''),API_KEY=process.env.API_KEY||'';
const DEFAULT_PLAY_PROVIDER=(process.env.DEFAULT_PLAY_PROVIDER||'castel').toLowerCase();
app.use(compression());app.use(express.json({limit:'1mb'}));app.use(express.urlencoded({extended:true}));app.use(express.static(path.join(__dirname,'public')));
const PROVIDERS={
'4khdhub':{home:'/api/4khdhub',search:'/api/4khdhub/search',details:'/api/4khdhub/details',gadget:'/api/4khdhub/gadget'},desiremovies:{home:'/api/desiremovies',search:'/api/desiremovies/search',details:'/api/desiremovies/details'},drive:{home:'/api/drive',search:'/api/drive/search',details:'/api/drive/details',mdrive:'/api/drive/mdrive'},netmirror:{home:'/api/netmirror',search:'/api/netmirror/search',details:'/api/netmirror/getpost',stream:'/api/netmirror/stream',eps:'/api/netmirror/eps'},movies4u:{home:'/api/movies4u',search:'/api/movies4u/search',details:'/api/movies4u/details',m4ulinks:'/api/movies4u/m4ulinks'},hdhub4u:{home:'/api/hdhub4u',search:'/api/hdhub4u/search',details:'/api/hdhub4u/details'},zeefliz:{home:'/api/zeefliz',search:'/api/zeefliz/search',details:'/api/zeefliz/details',nextdrive:'/api/zeefliz/nextdrive'},vega:{home:'/api/vega',search:'/api/vega/search',details:'/api/vega/details',nextdrive:'/api/vega/nextdrive'},zinkmovies:{home:'/api/zinkmovies',search:'/api/zinkmovies/search',details:'/api/zinkmovies/details',zinkcloud:'/api/zinkmovies/zinkcloud'},animesalt:{home:'/api/animesalt',search:'/api/animesalt/search',details:'/api/animesalt/details',stream:'/api/animesalt/stream'},animepahe:{home:'/api/animepahe',details:'/api/animepahe/details',stream:'/api/animepahe/stream'},castel:{stream:'/api/castel'},kmmovies:{home:'/api/kmmovies',search:'/api/kmmovies/search',details:'/api/kmmovies/details',magiclinks:'/api/kmmovies/magiclinks'},uhdmovies:{home:'/api/uhdmovies',search:'/api/uhdmovies/search',details:'/api/uhdmovies/details',tech:'/api/uhdmovies/tech'},mod:{home:'/api/mod',search:'/api/mod/search',details:'/api/mod/details',modpro:'/api/mod/modpro'},hubcloud:{extract:'/api/extractors/hubcloud'},gdflix:{extract:'/api/extractors/gdflix'}};
const SEARCH_PROVIDERS=['netmirror','4khdhub','movies4u','hdhub4u','zeefliz','vega','zinkmovies','animesalt','kmmovies','uhdmovies','mod','drive','desiremovies'];
const clean=v=>typeof v==='string'?v.trim():'';const first=(...v)=>v.map(clean).find(Boolean)||'';const year=v=>(String(v||'').match(/(?:19|20)\d{2}/)||[''])[0];
function typeOfItem(i,fb='movie'){const r=String(i?.type||i?.mediaType||i?.category||'').toLowerCase();if(r.includes('anime'))return'anime';if(r.includes('tv')||r.includes('show')||r.includes('series'))return'tv';return fb}
function walk(v,cb,seen=new Set()){if(v==null)return;if(typeof v==='object'){if(seen.has(v))return;seen.add(v)}cb(v);if(Array.isArray(v))v.forEach(x=>walk(x,cb,seen));else if(typeof v==='object')Object.values(v).forEach(x=>walk(x,cb,seen))}
function sources(input){const out=[];walk(input,n=>{if(typeof n==='string'){if(/^https?:\/\//i.test(n))out.push({name:'source',quality:'',url:n,headers:{}});return}if(!n||typeof n!=='object')return;const url=first(n.url,n.src,n.file,n.link,n.href,n.stream,n.streamUrl,n.m3u8,n.playlist,n.downloadUrl);if(!/^https?:\/\//i.test(url))return;out.push({name:first(n.name,n.server,n.provider,n.label,n.source)||'source',quality:first(n.quality,n.resolution,n.size),url,headers:n.headers&&typeof n.headers==='object'?n.headers:{}})});return[...new Map(out.map(s=>[s.url,s])).values()]}
function top(json){if(Array.isArray(json))return json;for(const k of['data','results','items','movies','shows','anime','posts','list','latest','trending'])if(Array.isArray(json?.[k]))return json[k];let f=[];walk(json,n=>{if(!f.length&&Array.isArray(n)&&n.some(x=>x&&typeof x==='object'))f=n});return f}
function item(i={},provider='',fb='movie'){const title=first(i.title,i.name,i.movie,i.post_title,i.label,i.original_title);return{provider,id:first(i.id,i.tmdb,i.tmdbId,i.postId,i.contentId,i.session),url:first(i.url,i.link,i.href,i.path,i.detailsUrl,i.postUrl,i.playUrl),title,year:first(i.year,i.releaseYear,year(title),year(i.date)),type:typeOfItem(i,fb),poster:first(i.poster,i.image,i.imageUrl,i.thumbnail,i.cover,i.logo,i.img),backdrop:first(i.backdrop,i.banner,i.background,i.cover),overview:first(i.overview,i.description,i.plot,i.synopsis,i.content,i.excerpt),sources:sources(i.sources||i.streams||i.links||i.downloads||i.servers)}}
function normalized(raw,provider,fb='movie'){const root=raw?.data||raw?.result||raw;const it=item(root&&!Array.isArray(root)?root:{},provider,fb);it.sources=sources(raw);return it}
async function api(endpoint,params={}){if(!API_BASE_URL||!API_KEY)throw Error('Missing API_BASE_URL or API_KEY env vars');if(String(endpoint).includes('/api/adult/'))throw Error('Adult provider routes are disabled');const u=new URL(API_BASE_URL+endpoint);Object.entries(params).forEach(([k,v])=>{if(v!==undefined&&v!==null&&v!=='')u.searchParams.set(k,String(v))});const r=await fetch(u,{headers:{'x-api-key':API_KEY,'Content-Type':'application/json',Accept:'application/json'}});const txt=await r.text();let data;try{data=JSON.parse(txt)}catch{data={raw:txt}}if(!r.ok)throw Error(data?.error||data?.message||`Provider HTTP ${r.status}`);return data}
function provider(name){const key=clean(name).toLowerCase();if(!PROVIDERS[key])throw Error('Unsupported provider');return[key,PROVIDERS[key]]}
function watchQs(req,type){const p=new URLSearchParams(req.query);const tmdb=clean(req.params.tmdb||req.query.tmdb||req.query.tmdbId||req.query.id);p.set('provider',clean(req.query.provider||DEFAULT_PLAY_PROVIDER).toLowerCase());p.set('type',type);if(tmdb){p.set('tmdb',tmdb);p.set('tmdbId',tmdb);p.set('id',tmdb)}if(type==='tv'){p.set('season',clean(req.params.season||req.query.season||'1'));p.set('episode',clean(req.params.episode||req.query.episode||'1'))}p.delete('mode');return p.toString()}
function playerHtml(q,label='Movie'){return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>SwiflyTV ${label}</title><script type="module" src="https://cdn.jsdelivr.net/npm/vidstack@latest/cdn/with-layouts/vidstack.js"></script><style>:root{color-scheme:dark}body{margin:0;background:#05060a;color:white;font-family:Inter,system-ui,sans-serif}.wrap{min-height:100vh;display:grid;place-items:center;padding:24px}.card{width:min(1200px,100%)}media-player{width:100%;aspect-ratio:16/9;border-radius:24px;overflow:hidden;background:#000;box-shadow:0 30px 80px #000}.msg{opacity:.8;margin:14px 4px}</style></head><body><div class="wrap"><div class="card"><media-player id="player" title="SwiflyTV" crossorigin playsinline><media-provider></media-provider><media-video-layout></media-video-layout></media-player><div id="msg" class="msg">Loading API source...</div></div></div><script>const qs=${JSON.stringify(q||'')}||new URLSearchParams(location.search).toString();const msg=document.getElementById('msg'),player=document.getElementById('player');const kind=u=>/\\.m3u8(\\?|#|$)/i.test(u)?'application/x-mpegurl':(/\\.mpd(\\?|#|$)/i.test(u)?'application/dash+xml':'video/mp4');fetch('/api/provider/embed?'+qs,{cache:'no-store'}).then(r=>r.json()).then(d=>{const s=(d.sources||[]).find(x=>x&&x.url);if(!s)throw Error(d.error||'No API source found');player.title=d.title||'SwiflyTV ${label}';player.src={src:s.url,type:kind(s.url)};msg.textContent=(s.name||'API source')+(s.quality?' • '+s.quality:'')}).catch(e=>{console.error(e);msg.textContent='Could not load API source: '+e.message});</script></body></html>`}
app.get('/health',(req,res)=>res.json({ok:true,providerApiConfigured:Boolean(API_BASE_URL&&API_KEY)}));
app.get('/api/providers',(req,res)=>res.json({ok:true,providers:Object.keys(PROVIDERS)}));
app.get('/api/provider/home',async(req,res)=>{try{const[p,cfg]=provider(req.query.provider||'netmirror');if(!cfg.home)return res.status(400).json({ok:false,error:'Provider has no home route'});const data=await api(cfg.home,{page:req.query.page||1,maxPages:req.query.maxPages});res.json({ok:true,provider:p,results:top(data).map(x=>item(x,p,p.includes('anime')?'anime':'movie'))})}catch(e){res.status(500).json({ok:false,error:e.message})}});
app.get('/api/provider/search',async(req,res)=>{const q=clean(req.query.q);if(!q)return res.status(400).json({ok:false,error:'Missing q'});const list=clean(req.query.provider)?[clean(req.query.provider).toLowerCase()]:SEARCH_PROVIDERS;const jobs=await Promise.all(list.map(async p=>{try{const cfg=PROVIDERS[p];if(!cfg?.search)return{provider:p,results:[]};const data=await api(cfg.search,{q,page:req.query.page||1});return{provider:p,results:top(data).map(x=>item(x,p,p.includes('anime')?'anime':'movie'))}}catch(e){return{provider:p,error:e.message,results:[]}}}));res.json({ok:true,q,results:jobs.flatMap(j=>j.results),errors:jobs.filter(j=>j.error)})});
app.get('/api/provider/details',async(req,res)=>{try{const[p,cfg]=provider(req.query.provider);if(!cfg.details)return res.status(400).json({ok:false,error:'Provider has no details route'});const data=await api(cfg.details,p==='netmirror'?{id:req.query.id||req.query.url,t:req.query.t}:{url:req.query.url});res.json({ok:true,provider:p,item:normalized(data,p,p.includes('anime')?'anime':'movie')})}catch(e){res.status(500).json({ok:false,error:e.message})}});
app.get('/api/provider/action',async(req,res)=>{try{const[p,cfg]=provider(req.query.provider);const action=clean(req.query.action).toLowerCase(),endpoint=cfg[action];if(!endpoint||endpoint.includes('/api/adult/'))return res.status(400).json({ok:false,error:'Unsupported action'});const params={...req.query};delete params.provider;delete params.action;const data=await api(endpoint,params);res.json({ok:true,provider:p,action,item:normalized(data,p,p.includes('anime')?'anime':'movie'),raw:data})}catch(e){res.status(500).json({ok:false,error:e.message})}});
app.get('/api/provider/embed',async(req,res)=>{try{const[p,cfg]=provider(req.query.provider||DEFAULT_PLAY_PROVIDER);const endpoint=cfg.stream||cfg.extract||cfg.details;if(!endpoint)return res.status(400).json({ok:false,error:'Provider has no embed route'});const params={...req.query};delete params.provider;const data=await api(endpoint,params);const it=normalized(data,p,p.includes('anime')?'anime':(req.query.type||'movie'));if(p==='animepahe')it.sources=it.sources.map(s=>({...s,headers:{Referer:'https://kwik.cx/',Origin:'https://kwik.cx',...(s.headers||{})}}));res.json({ok:it.sources.length>0,title:it.title,year:it.year,type:it.type,poster:it.poster,backdrop:it.backdrop,overview:it.overview,sources:it.sources})}catch(e){res.status(500).json({ok:false,error:e.message,sources:[]})}});
app.get(['/watch/movie/:tmdb','/movie/:tmdb/watch'],(req,res)=>res.send(playerHtml(watchQs(req,'movie'),'Movie')));
app.get(['/watch/tv/:tmdb/:season/:episode','/watch/show/:tmdb/:season/:episode'],(req,res)=>res.send(playerHtml(watchQs(req,'tv'),'TV')));
app.get(['/watch/tv/:tmdb','/watch/show/:tmdb'],(req,res)=>res.send(playerHtml(watchQs(req,'tv'),'TV')));
app.get('/watch-provider',(req,res)=>res.send(playerHtml(new URLSearchParams(req.query).toString(),'Provider')));
app.get('/',(req,res)=>res.send('<h1>SwiflyTV</h1><p>Backend provider routes ready. Movie watch pages use API sources through Vidstack.</p>'));
app.listen(PORT,()=>console.log(`SwiflyTV running on ${PORT}`));
